version: "3.2"

services:
  bot:
    container_name: "HashtagBot"
    image: "node:10"
    working_dir: "/app"
    depends_on:
      - postgres
    volumes:
      - "./:/app"
    environment:
      TOKEN:
      DATABASE_URI: postgresql://admin:iona@postgres/hashtag_bot
    command: "npx pm2 start ./src/hashtag.config.js --no-daemon"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: iona
      POSTGRES_DB: hashtag_bot
    volumes:
      - ./data:/var/lib/postgresql/data

