version: "3.2"

services:
  bot:
    container_name: "Hashtag Bot"
    image: "node:10"
    working_dir: "/app"
    volumes:
      - "./:/app"
     environment:
      TOKEN: 
      DATABASE_URI: postgresql://admin:iona@127.0.0.1:5432/hashtag_bot
    command: "npx pm2 start ./src/hashtag.config.js --no-daemon"

   db:
    container_name: "Hashtag Boot - PostgresSQL"
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: iona
      POSTGRES_DB: hashtag_bot
    volumes:
      - ./data:/var/lib/postgresql/data